# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest0601():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test0601(self):
    self.driver.get("https://www.baidu.com/")
    self.driver.set_window_size(1295, 695)
    self.driver.find_element(By.ID, "kw").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bdsug-store > span").click()
    self.driver.execute_script("window.scrollTo(0,0)")
  
